import './App.css'

const projects = [
  ['Minbako', 'SaaS komunikasi internal dengan forum diskusi, pengumuman, dan ruang berbagi ide.', 'React · Go · PostgreSQL', 'https://images.unsplash.com/photo-1556761175-b413da4baf72?w=900&q=80'],
  ['QuickCheck', 'Platform koreksi dokumen, latihan esai, dan interview untuk persiapan seleksi universitas.', 'Next.js · NestJS', 'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=900&q=80'],
  ['Kinesis HR', 'Platform otomasi rekrutmen untuk screening kandidat dan pengelolaan data pelamar.', 'Laravel · MySQL', 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=900&q=80'],
  ['Job Matcher AI', 'Platform yang menganalisis CV dan memberi rekomendasi pekerjaan relevan.', 'Next.js · Go · Python', 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=900&q=80'],
  ['Item Tracker', 'Aplikasi untuk membantu pengguna melacak dan menemukan kembali barang hilang.', 'React · Node.js', 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=900&q=80'],
  ['Ride Hailing API', 'Backend service untuk delivery dengan geo-spatial query dan update real-time.', 'Go · Redis', 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=900&q=80'],
]

const skillGroups = [
  ['Frontend', 'web', 'Building responsive and interactive user interfaces', ['HTML', 'CSS', 'Javascript', 'Typescript', 'React', 'Next.js']],
  ['Backend', 'dns', 'Building robust server-side applications and APIs', ['Go', 'Node.js', 'NestJS', 'Laravel', 'Spring Boot', 'PHP', 'Java']],
  ['Data & Caching', 'database', 'Storing, managing and caching application data', ['MySQL', 'PostgreSQL', 'MongoDB', 'Redis']],
  ['DevOps & Tools', 'build', 'Tools and environments for development and deployment', ['Docker', 'Linux', 'Git']],
]

const Icon = ({ children }) => <span className="material-symbols-outlined">{children}</span>
const SectionTitle = ({ children }) => <div className="section-title">{children}</div>
const Glass = ({ children, className = '' }) => <div className={`glass ${className}`}>{children}</div>

function App() {
  return <div className="site-shell">
    <nav className="navbar"><a className="brand" href="#hero">Rafly</a><div className="nav-links"><a className="active" href="#about">About</a><a href="#experience">Experience</a><a href="#skills">Skills</a><a href="#projects">Projects</a><a href="#contact">Contact</a></div><button className="nav-cv">Download CV</button><button className="menu-button" aria-label="Open menu"><Icon>menu</Icon></button></nav>
    <main>
      <section className="hero section" id="hero"><div className="hero-copy"><h1>Hello,<br />My name is <em>Rafly Hermansyah.</em><br />I am a Full Stack Developer specializing in <em>Frontend Developer.</em></h1><div className="social-row"><a href="#contact"><Icon>code</Icon></a><a href="#contact"><Icon>link</Icon></a><a href="#contact"><Icon>work</Icon></a></div><div className="button-row"><a className="button outline" href="#contact">CONTACT ME <Icon>person</Icon></a><a className="button primary" href="#contact">GET RESUME <Icon>download</Icon></a></div></div><Glass className="code-card"><div className="profile-line"><div className="avatar">RH</div><div><b>@raflyhermansyah_</b><small><i /> Online</small></div></div><div className="dots"><i /><i /><i /></div><pre><span>const</span> <b>developer</b> = {'{'}{`\n  `}<label>Name:</label> <strong>"Rafly Hermansyah"</strong>,{`\n  `}<label>Skills:</label> [<strong>"Javascript"</strong>, <strong>"Typescript"</strong>,{`\n           `}<strong>"Go"</strong>, <strong>"React.js"</strong>, <strong>"Next.js"</strong>,{`\n           `}<strong>"PostgreSQL"</strong>, <strong>"Docker"</strong>],{`\n  `}<label>HardWorker:</label> <b>true</b>,{`\n  `}<label>ProblemSolver:</label> <b>true</b>{`\n`}{'}'}</pre></Glass></section>

      <section className="section" id="about"><SectionTitle>About Me</SectionTitle><Glass className="about-box"><div className="portrait"><img alt="Rafly portrait" src="https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=700&q=85" /></div><div className="about-copy"><h2>Tentang <em>Saya</em></h2><p className="lead">Perpaduan logika kode dan estetika desain.</p><p>Full Stack Developer specializing in backend engineering, equipped with robust proficiency in Go, Node.js, and Laravel alongside solid frontend capabilities in React and Next.js.</p><p>Adept at architecting scalable systems, developing high-performance APIs, and managing complex databases. Committed to writing clean, maintainable code.</p><div className="stats"><div><b>2+</b><small>Years Experience</small></div><div><b>13+</b><small>Projects</small></div><div><b>15+</b><small>Tech Stack</small></div></div><button className="button ghost">Unduh CV <Icon>download</Icon></button></div></Glass></section>

      <section className="section" id="experience"><SectionTitle>Experiences</SectionTitle><div className="timeline"><Glass className="timeline-card featured"><div><small className="green">Jan 2025 - Present</small><h3>FULL STACK DEVELOPER <small>(Contract)</small></h3><p><Icon>business</Icon> BDBCompany, Inc. <Icon>location_on</Icon> Kyoto, Japan (Remote)</p></div><Icon>computer</Icon><details><summary>Show 7 key highlights <Icon>expand_more</Icon></summary><ul><li>Architected and developed enterprise-grade SaaS platforms</li><li>Implemented backend microservices using Go and Node.js</li><li>Optimized PostgreSQL queries, reducing response times by 40%</li></ul></details></Glass><Glass className="timeline-card"><div><small className="green">Aug 2024 - Nov 2024</small><h3>WEB DEVELOPER <small>(Internship)</small></h3><p><Icon>business</Icon> PT. Wesclic Indonesia Neotech <Icon>location_on</Icon> Yogyakarta, Indonesia</p></div><Icon>code</Icon></Glass><Glass className="timeline-card"><div><small className="green">Aug 2023 - Present</small><h3>MY ENGINEERING ARC</h3><a href="#projects">View on GitHub <Icon>open_in_new</Icon></a></div><Icon>school</Icon></Glass></div></section>

      <section className="section" id="skills"><SectionTitle>Skills</SectionTitle><div className="skills-list">{skillGroups.map(([name, icon, desc, items]) => <Glass className="skill-row" key={name}><div className="skill-intro"><div className="skill-icon"><Icon>{icon}</Icon></div><h3>{name}</h3><p>{desc}</p></div><div className="skill-items">{items.map(item => <div className="skill-item" key={item}><Icon>{item === 'Docker' ? 'directions_boat' : item === 'Git' ? 'account_tree' : item === 'Java' ? 'local_cafe' : 'code'}</Icon><small>{item}</small></div>)}</div></Glass>)}</div></section>

      <section className="section" id="projects"><SectionTitle>Projects</SectionTitle><div className="project-grid">{projects.map(([title, desc, stack, image]) => <Glass className="project-card" key={title}><div className="project-image"><img src={image} alt={`${title} project`} /></div><div className="project-content"><h3>{title}</h3><p>{desc}</p><div className="stack">{stack.split(' · ').map(item => <span key={item}>{item}</span>)}</div></div></Glass>)}</div><div className="pagination"><button>Previous</button><span>Page 1 of 2</span><button>Next</button></div></section>

      <section className="section" id="education"><SectionTitle>Education</SectionTitle><Glass className="education-card"><div><small className="green">Sep 2022 - Apr 2026</small><h3>BACHELOR OF INFORMATICS</h3><p>Universitas Amikom Yogyakarta</p><b className="green">GPA: 3.93 / 4.00</b></div><Icon>school</Icon><details open><summary>Show 3 achievements <Icon>expand_more</Icon></summary><ul><li>Relevant Coursework: Data Structures, Algorithms, Database Systems, Web Development</li><li>Active member of the University Programming Club</li><li>Participated in national level Hackathons</li></ul></details></Glass><SectionTitle>Bootcamps &amp; Training</SectionTitle><div className="bootcamp-grid">{[['Oct 2025 - Dec 2025', 'FULL STACK JAVA DEVELOPMENT BOOTCAMP', 'BPSDM Komdigi x Metrodata Academy'], ['Sep 2024 - Dec 2024', 'FULL STACK WEB DEVELOPMENT (MERN STACK)', 'Yayasan Adipurna Inovasi Asia (Vocasia)'], ['May 2024 - Jun 2024', 'BACKEND ENGINEERING TRAINEE', 'ProjectSprint.id']].map(([date, title, org]) => <Glass className="bootcamp" key={title}><small className="green">{date}</small><h3>{title}</h3><p>{org}</p><small>Show highlights <Icon>expand_more</Icon></small></Glass>)}</div></section>

      <section className="section contact-section" id="contact"><h2 className="contact-heading"><em>Contact</em></h2><p className="contact-intro">Saya selalu terbuka untuk proyek baru atau sekadar obrolan. Kirimkan sinyal Anda.</p><div className="contact-grid"><div className="contact-info"><b className="status">● SYSTEM STATUS: ONLINE</b><a className="glass contact-card" href="mailto:raflyhermansyah565@gmail.com"><Icon>mail</Icon><span><small>Email Me</small><b>raflyhermansyah565@gmail.com</b></span></a><a className="glass contact-card" href="https://wa.me/6282287680244"><Icon>chat</Icon><span><small>Chat WhatsApp</small><b>+62 822-8768-0244</b></span></a><div className="glass contact-card"><Icon>location_on</Icon><span><small>Location</small><b>Sleman, Daerah Istimewa Yogyakarta 55281</b></span></div><div className="social-row"><a href="#contact"><Icon>code</Icon></a><a href="#contact"><Icon>work</Icon></a><a href="mailto:raflyhermansyah565@gmail.com"><Icon>mail</Icon></a></div></div><form className="glass contact-form" onSubmit={e => e.preventDefault()}><h3><Icon>send</Icon> INITIATE DATA TRANSMISSION</h3><input placeholder="ID Pengirim / Nama" required /><input placeholder="Frekuensi Email" type="email" required /><textarea placeholder="Data Transmisi Pesan" required /><button className="send-button" type="submit">INISIASI TRANSMISI <Icon>arrow_outward</Icon></button></form></div></section>
    </main><footer><span>© 2024 Rafly Hermansyah. All rights reserved.</span><div><a href="#contact">LinkedIn</a><a href="#contact">GitHub</a><a href="mailto:raflyhermansyah565@gmail.com">Email</a></div></footer>
  </div>
}

export default App
